services:
  mysql:
    image: mysql:8.0
    container_name: coupon-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coupon
    volumes:
      - coupon-mysql-data:/var/lib/mysql

volumes:
  coupon-mysql-data: